In [2]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [3]:

import numpy as np

# 1. Instagram influencer follower counts
followers = np.array([1200, 15000, 67000, 340000, 1250000])

print("Followers:", followers)
print("Shape:", followers.shape)
print("Number of dimensions:", followers.ndim)
print("Data type:", followers.dtype)


# 2. Zomato order IDs for 10 consecutive orders
order_ids = np.arange(101, 111)

print("\nZomato Order IDs:", order_ids)
print("Size:", order_ids.size)


# 3. Spotify playlist 'like' identity matrix
like_matrix = np.eye(3)

# The diagonal values (1) represent a 'like' for each corresponding playlist item.
print("\nLike Identity Matrix:")
print(like_matrix)


# 4. Cricket scores converted to a NumPy array
scores = [45, 67, 120, 89, 54]
scores_array = np.array(scores)

print("\nCricket Scores:", scores_array)
print("Bytes per score:", scores_array.itemsize)

Followers: [   1200   15000   67000  340000 1250000]
Shape: (5,)
Number of dimensions: 1
Data type: int64

Zomato Order IDs: [101 102 103 104 105 106 107 108 109 110]
Size: 10

Like Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Cricket Scores: [ 45  67 120  89  54]
Bytes per score: 8


In [4]:
import numpy as np

print(np.__version__)

2.5.2
